<a href="https://colab.research.google.com/github/AishwaryaM15/Neural-Networks-and-Deep-Learning-Lab/blob/main/xor_gate_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#training data
X=np.array([[0,0],[0,1],[1,0],[1,1]])

#labels for training data
y=np.array([[0],[1],[1],[0]])

3. define weight variable

In [3]:
w11=np.asarray([1,1])
w12=np.asarray([1,1])
w2=np.asarray([-1,1])

B1=np.asarray([-1.5,-0.5])
B2=np.asarray([-0.5])

In [6]:
w11


array([1, 1])

In [7]:
w12

array([1, 1])

In [8]:
w2

array([-1,  1])

In [9]:
B1

array([-1.5, -0.5])

In [10]:
B2

array([-0.5])

In [12]:
x=X[0]
print(x)

[0 0]


In [13]:
len(w11)

2

In [19]:
def summation(x,w11,w12,B1):
  sumh=[0,0]
  for i in range(len(x)):
    sumh[i]=(x[0]*w11[i]+x[1]*w12[i]+B1[i])
  return sumh

In [20]:
sumv=summation(x,w11,w12,B1)
print(sumv)

[-1.5, -0.5]


In [21]:
def Heaviside(net):
  if net>=0:
    return 1
  else:
    return 0

In [23]:
hidden=[0,0]
for i in range(len(sumv)):
  hidden[i]=Heaviside(sumv[i])

print(hidden)

[0, 0]


In [24]:
sumo=np.dot(hidden,w2)+B2[0]
y_pred=Heaviside(sumo)
print(y_pred)

0


In [25]:
y_pred=[]
for i in range(X.shape[0]):
  x=X[i]
  sumv=summation(x,w11,w12,B1)
  hidden=[0,0]
  for i in range (len(sumv)):
    hidden[i]=Heaviside(sumv[i])
  sumo=np.dot(hidden,w2)+B2[0]
  y_pred.append(Heaviside(sumo))

In [26]:
y_pred

[0, 1, 1, 0]